name: Lint

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: .go-version

      - name: check go.mod
        run: |
          go mod tidy && git diff --exit-code
          go mod verify

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true

      - name: go-licenser
        run: |-
          go get github.com/elastic/go-licenser
          go run github.com/elastic/go-licenser -d
