name: Lint

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: .go-version

      - name: check go.mod
        run: |
          go mod tidy && git diff --exit-code
          go mod verify

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true

      - name: Lint
        run: |-
          go get github.com/elastic/go-licenser
          go-licenser -d
